services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js"
    volumes:
      - nats_data:/data

  subnet42:
    image: masaengineering/subnet-42:latest
    environment:
      - NATS_URL=nats://nats:4222
      - TEE_NATS_CHANNEL_NAME=miners
      - DEBUG=true
      - ENV=dev
      - ROLE=miner
      - BT_WALLET_PATH=${BT_WALLET_PATH:-/root/.bittensor}
      - BT_WALLET_NAME=${BT_WALLET_NAME:-default}
      - BT_HOTKEY_NAME=${BT_HOTKEY_NAME:-default}
    volumes:
      - ${BT_WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ./.env:/app/.env
      - ./scripts:/app/scripts
      - ./miner:/app/miner
      - ./validator:/app/validator
      - ./interfaces:/app/interfaces
      - ./neurons:/app/neurons
    depends_on:
      - nats

  tee-worker:
    image: masaengineering/subnet-42:latest
    environment:
      - NATS_URL=nats://nats:4222
      - TEE_NATS_CHANNEL_NAME=miners
      - ROLE=tee-worker
      - BT_WALLET_PATH=${BT_WALLET_PATH:-/root/.bittensor}
      - BT_WALLET_NAME=${BT_WALLET_NAME:-default}
      - BT_HOTKEY_NAME=${BT_HOTKEY_NAME:-default}
    command: ["python", "-m", "tee_worker.worker"]
    volumes:
      - ${BT_WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ./.env:/app/.env
    depends_on:
      - nats

volumes:
  nats_data: 