services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js"
    volumes:
      - nats_data:/data

  subnet42:
    image: masaengineering/subnet-42:latest
    environment:
      - NATS_URL=nats://nats:4222
      - TEE_NATS_CHANNEL_NAME=miners
      - DEBUG=true
      - ENV=dev
      - ROLE=miner
    volumes:
      - ~/.bittensor:/root/.bittensor
      - ./.env:/app/.env
      - ./scripts:/app/scripts
      - ./miner:/app/miner
      - ./validator:/app/validator
      - ./interfaces:/app/interfaces
      - ./neurons:/app/neurons
    depends_on:
      - nats

  tee-worker:
    image: masaengineering/subnet-42:latest
    environment:
      - NATS_URL=nats://nats:4222
      - TEE_NATS_CHANNEL_NAME=miners
      - ROLE=tee-worker
    volumes:
      - ~/.bittensor:/root/.bittensor
      - ./.env:/app/.env
    depends_on:
      - nats

volumes:
  nats_data: 