services:
  neuron:
    profiles: ["miner", "miner-vpn", "validator", "validator-tee"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
    deploy:
      resources:
        limits:
          memory: ${NEURON_MEMORY_LIMIT:-0}
          cpus: ${NEURON_CPU_LIMIT:-0}
        reservations:
          memory: ${NEURON_MEMORY_RESERVATION:-0}
          cpus: ${NEURON_CPU_RESERVATION:-0}
    ports:
      - "${VALIDATOR_PORT:-8090}:${VALIDATOR_PORT:-8090}"
      - "${MINER_PORT:-8091}:${MINER_PORT:-8091}"
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  worker:
    profiles: ["miner", "validator-tee"]
    image: masaengineering/tee-worker:latest
    pull_policy: always
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${WORKER_MEMORY_LIMIT:-0}
          cpus: ${WORKER_CPU_LIMIT:-0}
        reservations:
          memory: ${WORKER_MEMORY_RESERVATION:-0}
          cpus: ${WORKER_CPU_RESERVATION:-0}
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    network_mode: host
    volumes:
      - ./.env:/home/masa/.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker-vpn:
    profiles: ["miner-vpn"]
    image: masaengineering/tee-worker:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${WORKER_MEMORY_LIMIT:-0}
          cpus: ${WORKER_CPU_LIMIT:-0}
        reservations:
          memory: ${WORKER_MEMORY_RESERVATION:-0}
          cpus: ${WORKER_CPU_RESERVATION:-0}
    ports:
      - "${TEE_PORT:-8080}:${TEE_PORT:-8080}"
    environment:
      - http_proxy=http://vpn:${VPN_PORT:-3128}
      - https_proxy=http://vpn:${VPN_PORT:-3128}
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - ./.env:/home/masa/.env
      - ./cookies:/home/masa
    depends_on:
      vpn:
        condition: service_started
      cookie-generator:
        condition: service_completed_successfully
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vpn:
    profiles: ["cookies", "miner-vpn", "vpn"]
    build:
      context: .
      dockerfile: Dockerfile.vpn
    image: vpn-service:latest
    pull_policy: never
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "${VPN_PORT:-3128}:3128"
    volumes:
      - ./config.ovpn:/etc/openvpn/config/config.ovpn
      - ./auth.txt:/etc/openvpn/config/auth.txt
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:${VPN_PORT:-3128}", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cookie-generator:
    profiles: ["cookies", "miner-vpn"]
    image: cookie-generator:latest
    pull_policy: never
    depends_on:
      vpn:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.cookies
    volumes:
      - ./.env:/app/.env
      - ./cookies:/app/cookies
    environment:
      - PYTHONUNBUFFERED=1
      - http_proxy=http://vpn:${VPN_PORT:-3128}
      - https_proxy=http://vpn:${VPN_PORT:-3128}
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"