services:
  neuron:
    profiles: ["miner", "validator"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    ports:
      - "${VALIDATOR_PORT:-8092}:8092"
      - "${MINER_PORT:-8091}:8091"
    # volumes:
    #   - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
    environment:
      - ROLE=${ROLE:-miner}
      - WALLET_NAME=${WALLET_NAME:-default}
      - VALIDATOR_WALLET_NAME=${VALIDATOR_WALLET_NAME:-default}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-test}
      - NETUID=${NETUID:-165}
      - AUTO_GENERATE_HOTKEY=${AUTO_GENERATE_HOTKEY}
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    profiles: ["miner"]
    image: masaengineering/tee-worker:main
    pull_policy: always
    environment:
      - ROLE=validator
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    # network_mode: host
    network_mode: "service:expressvpn"
    depends_on:
      - expressvpn
    volumes:
      - ./.env:/home/masa/.env  # This maps the .env file to /home/masa/.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vpn:
    profiles: ["miner", "test"]
    image: ubuntu:22.04
    container_name: expressvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./expressvpn/config:/etc/openvpn/config
    command: >
      bash -c "apt-get update && 
      apt-get install -y openvpn curl && 
      openvpn --config /etc/openvpn/config/expressvpn.ovpn --auth-user-pass /etc/openvpn/config/auth.txt --auth-nocache"
    restart: unless-stopped