services:
  subnet42-miner:
    image: masaengineering/subnet42:latest
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    ports:
      - "${MINER_PORT:-8082}:8081"
    environment:
      - ROLE=miner
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ${CONFIG_PATH:-./config}:/app/config
      - ./neurons:/app/neurons
      - ./miner:/app/miner
      - ./validator:/app/validator
      - ./interfaces:/app/interfaces
      - ./scripts:/app/scripts
    depends_on:
      nats:
        condition: service_healthy
      tee-worker:
        condition: service_started

  tee-worker:
    image: masaengineering/tee-worker:latest
    environment:
      - ROLE=validator
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ${CONFIG_PATH:-./config}:/app/config
      - ./neurons:/app/neurons:ro
      - ./miner:/app/miner:ro
      - ./validator:/app/validator:ro
      - ./interfaces:/app/interfaces:ro
      - ./scripts:/app/scripts:ro

volumes:
  nats_data: