services:
  neuron:
    profiles: ["miner", "validator"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    container_name: ${ROLE:-miner}  # Will be "miner" or "validator" based on ROLE env var
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    ports:
      - "${VALIDATOR_PORT:-8092}:8092"
      - "${MINER_PORT:-8091}:8091"
    # volumes:
    #   - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
    environment:
      - ROLE=${ROLE:-miner}
      - WALLET_NAME=${WALLET_NAME:-default}
      - VALIDATOR_WALLET_NAME=${VALIDATOR_WALLET_NAME:-default}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-test}
      - NETUID=${NETUID:-165}
      - AUTO_GENERATE_HOTKEY=${AUTO_GENERATE_HOTKEY}
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker:
    profiles: ["miner"]
    image: masaengineering/tee-worker:main
    pull_policy: always
    container_name: worker
    ports:
      - "8080:8080"  # Expose port 8080 directly
    environment:
      - ROLE=validator
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    # Remove the network_mode line
    depends_on:
      - vpn
    volumes:
      - ./.env:/home/masa/.env
    # Add this to set up routing through the VPN for outbound traffic
    entrypoint: >
      /bin/bash -c "
      apt-get update && 
      apt-get install -y iproute2 && 
      ip route del default || true && 
      ip route add default via $(getent hosts vpn | awk '{ print $1 }') && 
      /home/masa/entrypoint.sh"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vpn:
    profiles: ["miner", "test"]
    image: ubuntu:22.04
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./expressvpn/config:/etc/openvpn/config
    command: >
      bash -c "apt-get update && 
      apt-get install -y openvpn curl iptables net-tools && 
      echo 'net.ipv4.ip_forward=1' > /etc/sysctl.conf && 
      sysctl -p && 
      iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE && 
      iptables -A FORWARD -i eth0 -o tun0 -j ACCEPT && 
      iptables -A FORWARD -i tun0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT && 
      openvpn --config /etc/openvpn/config/expressvpn.ovpn --auth-user-pass /etc/openvpn/config/auth.txt --auth-nocache"
    restart: unless-stopped