services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: ["--jetstream"]
    healthcheck:
      test: ["CMD", "nats-server", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  subnet42:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROLE=${ROLE:-miner}
      - NETWORK=${NETWORK:-test}
      - WALLET_PATH=${WALLET_PATH:-/root/.bittensor}
      - WALLET_NAME=${WALLET_NAME:-default}
      - WALLET_HOTKEY=${WALLET_HOTKEY:-default}
      - NATS_URL=nats://nats:4222
      - TEE_WORKER_URL=http://tee-worker:8000
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ${CONFIG_PATH:-./config}:/app/config
    depends_on:
      nats:
        condition: service_healthy
      tee-worker:
        condition: service_started

  tee-worker:
    image: masaengineering/tee-worker:latest
    environment:
      - OE_SIMULATION=1
    depends_on:
      - nats

volumes:
  nats_data: 