services:
  neuron:
    profiles: ["miner", "miner-vpn", "validator"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    container_name: ${ROLE:-miner}
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    ports:
      - "${VALIDATOR_PORT:-8092}:8092"
      - "${MINER_PORT:-8091}:8091"
    # volumes:
    #   - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
    environment:
      - ROLE=${ROLE:-miner}
      - WALLET_NAME=${WALLET_NAME:-default}
      - VALIDATOR_WALLET_NAME=${VALIDATOR_WALLET_NAME:-default}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-test}
      - NETUID=${NETUID:-165}
      - AUTO_GENERATE_HOTKEY=${AUTO_GENERATE_HOTKEY}
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  worker:
    profiles: ["miner"]
    image: masaengineering/tee-worker:main
    pull_policy: always
    container_name: worker
    environment:
      - ROLE=validator
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    network_mode: host
    volumes:
      - ./.env:/home/masa/.env  # This maps the .env file to /home/masa/.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker-vpn:
    profiles: ["miner-vpn"]
    image: masaengineering/tee-worker:main
    pull_policy: always
    container_name: worker-vpn
    ports:
      - "8080:8080"
    environment:
      - ROLE=validator
      - http_proxy=http://vpn:3128
      - https_proxy=http://vpn:3128
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - ./.env:/home/masa/.env
      # TODO: update to your twitter username this to the actual username
      # TODO: you can add as many cookie files as you want, each for a different twitter account
      - ./cookies.json:/home/masa/<username>_twitter_cookies.json
    depends_on:
      - vpn
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vpn:
    profiles: ["miner-vpn"]
    image: ubuntu:22.04
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "3128:3128"
    volumes:
      - ./config.ovpn:/etc/openvpn/config/config.ovpn
      - ./auth.txt:/etc/openvpn/config/auth.txt
    command: >
      bash -c "apt-get update && 
      apt-get install -y openvpn curl iptables tinyproxy &&
      echo 'net.ipv4.ip_forward=1' > /etc/sysctl.conf &&
      sysctl -p &&
      echo 'Allow 0.0.0.0/0' >> /etc/tinyproxy/tinyproxy.conf &&
      sed -i 's/Port 8888/Port 3128/g' /etc/tinyproxy/tinyproxy.conf &&
      service tinyproxy restart &&
      iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE &&
      openvpn --config /etc/openvpn/config/config.ovpn --auth-user-pass /etc/openvpn/config/auth.txt --auth-nocache --verb 3"
    restart: unless-stopped