services:
  nats:
    profiles:
      - nats
      - validator
    image: nats:latest
    pull_policy: always
    ports:
      - "4222:4222"
    command: ["--jetstream"]
    healthcheck:
      test: ["CMD", "nats-server", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  subnet42:
    profiles: ["miner", "validator"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    ports:
      - "${MINER_PORT:-8082}:8081"
    environment:
      - ROLE=${ROLE:-miner}
      - AUTO_GENERATE_HOTKEY=${AUTO_GENERATE_HOTKEY}
    command: ["/bin/bash", "/app/entrypoint.sh"]
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ${CONFIG_PATH:-./config}:/app/config
      - ./neurons:/app/neurons
      - ./miner:/app/miner
      - ./validator:/app/validator
      - ./interfaces:/app/interfaces
      - ./scripts:/app/scripts

  tee-worker:
    profiles: ["miner"]
    image: masaengineering/tee-worker:latest
    pull_policy: always
    environment:
      - ROLE=validator
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ${CONFIG_PATH:-./config}:/app/config
      - ./neurons:/app/neurons
      - ./miner:/app/miner
      - ./validator:/app/validator
      - ./interfaces:/app/interfaces
      - ./scripts:/app/scripts

volumes:
  nats_data: