services:
  neuron:
    profiles: ["miner", "miner-vpn", "validator", "validator-tee"]
    image: masaengineering/subnet-42:latest
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        when:
          variable: BUILD_LOCAL
          value: "true"
    # volumes:
    #   - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
    deploy:
      resources:
        ${NEURON_RESOURCES:-{}}
    ports:
      - "${VALIDATOR_PORT:-8090}:${VALIDATOR_PORT:-8090}"
      - "${MINER_PORT:-8091}:${MINER_PORT:-8091}"
    environment:
      - ROLE=${ROLE:-miner}
      - WALLET_NAME=${WALLET_NAME:-default}
      - VALIDATOR_WALLET_NAME=${VALIDATOR_WALLET_NAME:-default}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-test}
      - NETUID=${NETUID:-165}
      - AUTO_GENERATE_HOTKEY=${AUTO_GENERATE_HOTKEY}
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  worker:
    profiles: ["miner", "validator-tee"]
    image: masaengineering/tee-worker:main
    pull_policy: always
    deploy:
      resources:
        ${WORKER_RESOURCES:-{}}
    environment:
      - ROLE=validator
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    network_mode: host
    volumes:
      - ./.env:/home/masa/.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  worker-vpn:
    profiles: ["miner-vpn"]
    image: masaengineering/tee-worker:main
    pull_policy: always
    deploy:
      resources:
        ${WORKER_VPN_RESOURCES:-{}}
    ports:
      - "${TEE_PORT:-8080}:${TEE_PORT:-8080}"
    environment:
      - ROLE=validator
      - http_proxy=http://vpn:${VPN_PORT:-3128}
      - https_proxy=http://vpn:${VPN_PORT:-3128}
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - ./.env:/home/masa/.env
      - ./cookies.json:/home/masa/<your-username>_twitter_cookies.json
    depends_on:
      - vpn
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  vpn:
    profiles: ["miner-vpn"]
    image: ubuntu:22.04
    deploy:
      resources:
        ${VPN_RESOURCES:-{}}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "${VPN_PORT:-3128}:3128"
    volumes:
      - ./config.ovpn:/etc/openvpn/config/config.ovpn
      - ./auth.txt:/etc/openvpn/config/auth.txt
    command: >
      bash -c "apt-get update && 
      apt-get install -y openvpn curl iptables tinyproxy &&
      echo 'net.ipv4.ip_forward=1' > /etc/sysctl.conf &&
      sysctl -p &&
      echo 'Allow 0.0.0.0/0' >> /etc/tinyproxy/tinyproxy.conf &&
      sed -i 's/Port 8888/Port ${VPN_PORT:-3128}/g' /etc/tinyproxy/tinyproxy.conf &&
      service tinyproxy restart &&
      iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE &&
      openvpn --config /etc/openvpn/config/config.ovpn --auth-user-pass /etc/openvpn/config/auth.txt --auth-nocache --verb 3"
    restart: unless-stopped