apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: subnet42-miner
spec:
  serviceName: subnet42-miner
  replicas: 1  # Set this to desired number of miners
  selector:
    matchLabels:
      app: subnet42-miner
  template:
    metadata:
      labels:
        app: subnet42-miner
    spec:
      serviceAccountName: subnet42-miner  # Will be created separately
      containers:
      - name: miner
        image: masaengineering/subnet42:latest
        command: ["/bin/bash"]
        args: ["/app/entrypoint.sh"]
        env:
        - name: COLDKEY_MNEMONIC
          valueFrom:
            secretKeyRef:
              name: bittensor-miner-mnemonics
              key: coldkey-mnemonic
        - name: INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NETUID
          value: "165"  # Change to 59 for mainnet
        - name: SUBTENSOR_NETWORK
          value: "finney"  # Change to "test" for testnet
        - name: ROLE
          value: "miner"
        - name: AUTO_GENERATE_HOTKEY
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: subnet42-miner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: subnet42-miner-secret-manager
subjects:
- kind: ServiceAccount
  name: subnet42-miner
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io 